### ISSUE TITLE
Problem with 'postMessage'

### ISSUE THREAD

**Issue by jmrosdev** [rudrakshpathak/angular2-google-login#1]
Hello, I have this error when accessing my api created with gae and trying to connect I get this error. I have been reading that it may be CORS problem. Is there a solution with your component?

This error
zone.js:170 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'http://http%3a%2f%2flocalhost%3a4200' in a call to 'postMessage'.
    at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.es.g2UIZmypqfg.O/m…1/ed=1/am=AQ/rs=AGLTcCNdifD38XqbW-qfz3LDxdT8ceyDJQ/cb=gapi.loaded_0:87:445
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:118322:31)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:118121:47)
    at ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:118375:38)
    at data.args.(anonymous function) (http://localhost:4200/vendor.bundle.js:119536:29)

**Comment by rudrakshpathak** [comment]
Hi jmrosdev,

Can you please share your code snippet and the screenshot of error.

**Comment by jmrosdev** [comment]
Yes! https://gist.github.com/jmrosdev/f508ba837179270d60bbb29a56143ab4 code and https://drive.google.com/file/d/0B8IPnqoJODlZMTNLRGF4VTdIVnc/view?usp=sharing screenshot of error

**Comment by rudrakshpathak** [comment]
Hi,

I did some research about this error. Although I wasn't able to produce the same error in my environment, but following can be the reasons for this error -

1. CORS error
2. Target origin being https
3. URL is not correct

You can read more about this error here - 

https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage

https://stackoverflow.com/questions/27710697/uncaught-syntaxerror-failed-to-execute-postmessage-on-window-invalid-targe
