### ISSUE TITLE
gapi is not defined

### ISSUE THREAD

**Issue by ghost** [rudrakshpathak/angular2-google-login#2]
I have gapi is not defined

What I have to put in ngAfterViewInit ?

Thx

**Comment by matty22** [comment]
Same issue. The README is not clear on how to correct this problem.

**Comment by rudrakshpathak** [comment]
Hi @ducmaxime ,

You can use this code in `ngAfterViewInit` -

`AppGlobals.GOOGLE_CLIENT_ID = 'SECRET_CLIENT_ID';
 this.getData();`

And to resolve the `gapi` not defined issue, you can increase the time out. But I'm searching a better solution for it. For now if you increase the time out, it will work fine.

**Comment by cues7aaaa** [comment]
@rudrakshpathak Increase the timeout? Which timeout?

**Comment by rudrakshpathak** [comment]
`ngOnInit() {
   //Set your Google Client ID here
   AppGlobals.GOOGLE_CLIENT_ID = 'SECRET_CLIENT_ID';
   this.getData();
   setTimeout(() => { this.googleAuthenticate() }, 50);
}`

Time out in login.component.ts

**Comment by rudrakshpathak** [comment]
```javascript
ngOnInit() {
   //Set your Google Client ID here
   AppGlobals.GOOGLE_CLIENT_ID = 'SECRET_CLIENT_ID';
   this.getData();
   setTimeout(() => { this.googleAuthenticate() }, 50);
}
```

Set timeout in app.component.ts

**Comment by cues7aaaa** [comment]
It's working!!! Thanks so much Rudraksh!!

**Comment by bukialabi** [comment]
I still had the issue even with the timeout. What solved it for me was removing "async" and "defer" from the script tag in my index page. So now, the script tag is just:
<script src="https://apis.google.com/js/platform.js"></script>

**Comment by rudrakshpathak** [comment]
Hi,

I hope everything is working fine. I'm closing this issue now.
@bukialabi Thanks for the suggestion. I'll test it and implement in the next release.
