### ISSUE TITLE
Typescript error while compiling

### ISSUE THREAD

**Issue by abhilashrathod** [rudrakshpathak/angular2-google-login#3]
hello there, 
I am facing this issue, while the compilation of project. 
Project config: Angular 4.0 with Typescript 2.3.4

```
ERROR in ./~/angular2-google-login/index.ts
Module build failed: Error: Typescript emitted no output for /opt/lampp/htdocs/we-love-travel/node_modules/angular2-google-login/index.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358

```

Would you please help me with this.

**Comment by rudrakshpathak** [comment]
Hi abhilashrathod,

I created this package to be used in Angular 2. Not sure what causing this error. I will check it for sure and if there is a solution/fix for it, I will update the package.

**Comment by rudrakshpathak** [comment]
Hi Abhilash,

I hope everything will be fine. I'm closing this issue now.
