### ISSUE TITLE
Another version

### ISSUE THREAD

**Issue by YuriFontella** [rudrakshpathak/angular2-google-login#4]
Based on your service, I've refactored your code for my needs ... inspired me, thank you.

I'm just having popup problem blocked from the login screen, and I can not figure out what it might be associated with.

And the logout does not display errors, but it is not as efficient.

https://gist.github.com/YuriFontella/2c993aefebebfdaa1e7c84b649e0d257

**Comment by rudrakshpathak** [comment]
Hi YuriFontella,

Can you please share your code so that I can check what causing the error in your popup design. And can you please explain what sort of errors you want to show in logout functionality?
Also I would love to have some suggestions in case logout is not efficient.

**Comment by YuriFontella** [comment]
I ended up implementing it with the attachClickHandler.
Easier and more functional.
