### ISSUE TITLE
Two clicks necessary for login

### ISSUE THREAD

**Issue by gkTim** [rudrakshpathak/angular2-google-login#5]
Hi,

we use your module for facebook login and it works great.
Except that the user needs to click two times on the login button to login.
The first time the button is clicked only a few files are fetched:

```
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.wObLpOs26SA.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCPoqQVPsEmjbh64D3n5K0kPTFfsEA/cb=gapi.loaded_0

https://accounts.google.com/o/oauth2/iframe

https://ssl.gstatic.com/accounts/o/2836349087-idpiframe.js
```

The second click then triggers the login.

Is this a known issue?

Greetz
Tim

**Comment by rudrakshpathak** [comment]
Hi Tim,

I'll look into this issue and will resolve it as soon as possible.

Regards ,
Rudraksh

**Comment by IuriiKryventsov** [comment]
@gkTim Hi! Try to place this._googleAuth.authenticateUser call in ngOnInit() or constructor.

**Comment by skavinvarnan** [comment]
@IuriiKryventsov still it doesn't work

**Comment by joe455** [comment]
same issue for me too :(

**Comment by joe455** [comment]
@IuriiKryventsov Thanks..It did the trick!!!
