### ISSUE TITLE
Good to rename AuthService

### ISSUE THREAD

**Issue by chriscurnow** [rudrakshpathak/angular2-google-login#6]
AuthhService is a very generic name and could easily conflict with some other npm module.

Perhaps "GoogleAuthService".

Up to you of course. Just a suggestion.

**Comment by rudrakshpathak** [comment]
A very good suggestion Chris. Thanks. I'll implement it in the next release.

**Comment by chriscurnow** [comment]
You're welcome. I mainly noticed it because I have an internally defined AuthService.

It was no problem for me to rename my service but if it was in an external npm module it would be harder.

I've only had a brief look at your module so far. I will experiment more as time permits. It looks like a great idea which will be very useful. Thanks for publishing it.

**Comment by emmgfx** [comment]
@chriscurnow I think that you don't need to rename your own AuthService. Instead, call this with an alias, like:

`import { AuthService as GoogleAuthService, AppGlobals } from 'angular2-google-login';`

Hope that in the future the AuthService was renamed to avoid confusion : )
