### ISSUE TITLE
Valid error results in: TypeError: Cannot set property 'error' of undefined

### ISSUE THREAD

**Issue by jasonburrows** [rudrakshpathak/angular2-google-login#7]
I experienced a valid error (was sending requests from an unknown origin), but the error was not handled correctly by this module:

auth.service.ts:46 Uncaught TypeError: Cannot set property 'error' of undefined

**Comment by rohanamhi** [comment]
+1

**Comment by rudrakshpathak** [comment]
Thank you for reporting the error. I'll take a look into this issue.

**Comment by marty331** [comment]
Any updates on this?  I am getting this issue as well.

**Comment by rudrakshpathak** [comment]
Unfortunately Im not able to reproduce the error. @jasonburrows, @marty331 can you please share your code snippet?

**Comment by marty331** [comment]
Inside the auth2.attachClickHandler in the error portion, you reference "this.error", but error is not defined at the class level but it is defined at the function level.  So either define it there or remove the "this." to use the function variable or define error at the class level.

**Comment by rudrakshpathak** [comment]
Ok. Thanks for the information. I will test it and will release it in next build.
