### ISSUE TITLE
Logout redirect

### ISSUE THREAD

**Issue by PodviaznikovPavlo** [rudrakshpathak/angular2-google-login#9]
hi, i'm wondering if there is a way to configure redirect after .userLogout() ?
I can see that "homeUrl" is hardcoded to "localhost: 4200" but it would be nice to have a chance to configure redirect link. 
I think we can use "AppGlobals" to specify redirect url.

**Comment by rudrakshpathak** [comment]
Hi Pavel,

Thank you for your suggestion. I will consider this change in the next build.
